
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  base_pos_controller:
    type: effort_controllers/JointPositionController
    joint: base_brazo
    pid: {p: 60.0, i: 5.0, d: 1.0}
    
  arti1_pos_controller:
    type: effort_controllers/JointPositionController
    joint: arti1
    pid: {p: 60.0, i: 5.0, d: 1.0}
    
  arti2_pos_controller:
    type: effort_controllers/JointPositionController
    joint: arti2
    pid: {p: 60.0, i: 5.0, d: 1.0}
    
  arti3_pos_controller:
    type: effort_controllers/JointPositionController
    joint: arti3
    pid: {p: 60.0, i: 5.0, d: 1.0}
    
  pinza_pos_controller:
    type: effort_controllers/JointPositionController
    joint: pinza
    pid: {p: 2.0, i: 0.5, d: 0.0}
    
  # Wheels transmission ----------------------------------------
  
  right_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}
    
  left_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}
  
  # Velocity Controllers ---------------------------------------
  base_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: base_brazo
    pid: {p: 2.0, i: 0.5, d: 0.0}
    
  arti1_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: arti1
    pid: {p: 2.0, i: 0.5, d: 0.0}
    
  arti2_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: arti2
    pid: {p: 2.0, i: 0.5, d: 0.0}
    
  arti3_vel_controller:
   type: effort_controllers/JointVelocityController
   joint: arti3
   pid: {p: 2.0, i: 0.5, d: 0.0}      

  pinza_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: pinza
    pid: {p: 2.0, i: 0.5, d: 0.0}

  brazo_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - base_brazo
      - arti1
      - arti2
      - arti3

    gains: # Required because we're controlling an effort interface
      base_brazo: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}      
      arti1: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}
      arti2: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}
      arti3: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}
