gazebo_ros_control/pid_gains:
  base_brazo: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}
  arti1: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}
  arti2: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}
  arti3: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}
  pinza: {p: 2.0, i: 0.6, d: 0.3, i_clamp: 10}
