/* Auto-generated by genmsg_cpp for file /home/user/ROS_fuerte_workspace/sandbox/MB_robot/myrabot_arm_base/msg/WriteServos.msg */
#ifndef MYRABOT_ARM_BASE_MESSAGE_WRITESERVOS_H
#define MYRABOT_ARM_BASE_MESSAGE_WRITESERVOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "myrabot_arm_base/Servos.h"
#include "myrabot_arm_base/Servos.h"
#include "myrabot_arm_base/Servos.h"

namespace myrabot_arm_base
{
template <class ContainerAllocator>
struct WriteServos_ {
  typedef WriteServos_<ContainerAllocator> Type;

  WriteServos_()
  : posicion()
  , velocidad()
  , par()
  {
  }

  WriteServos_(const ContainerAllocator& _alloc)
  : posicion(_alloc)
  , velocidad(_alloc)
  , par(_alloc)
  {
  }

  typedef  ::myrabot_arm_base::Servos_<ContainerAllocator>  _posicion_type;
   ::myrabot_arm_base::Servos_<ContainerAllocator>  posicion;

  typedef  ::myrabot_arm_base::Servos_<ContainerAllocator>  _velocidad_type;
   ::myrabot_arm_base::Servos_<ContainerAllocator>  velocidad;

  typedef  ::myrabot_arm_base::Servos_<ContainerAllocator>  _par_type;
   ::myrabot_arm_base::Servos_<ContainerAllocator>  par;


  typedef boost::shared_ptr< ::myrabot_arm_base::WriteServos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myrabot_arm_base::WriteServos_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct WriteServos
typedef  ::myrabot_arm_base::WriteServos_<std::allocator<void> > WriteServos;

typedef boost::shared_ptr< ::myrabot_arm_base::WriteServos> WriteServosPtr;
typedef boost::shared_ptr< ::myrabot_arm_base::WriteServos const> WriteServosConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::myrabot_arm_base::WriteServos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::myrabot_arm_base::WriteServos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace myrabot_arm_base

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::myrabot_arm_base::WriteServos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::myrabot_arm_base::WriteServos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::myrabot_arm_base::WriteServos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9551946156ffa6c4d13c8c60abd574c1";
  }

  static const char* value(const  ::myrabot_arm_base::WriteServos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9551946156ffa6c4ULL;
  static const uint64_t static_value2 = 0xd13c8c60abd574c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::myrabot_arm_base::WriteServos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "myrabot_arm_base/WriteServos";
  }

  static const char* value(const  ::myrabot_arm_base::WriteServos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::myrabot_arm_base::WriteServos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Servos posicion\n\
Servos velocidad\n\
Servos par\n\
\n\
================================================================================\n\
MSG: myrabot_arm_base/Servos\n\
int16 base\n\
int16 arti1\n\
int16 arti2\n\
int16 arti3\n\
int16 pinza\n\
\n\
";
  }

  static const char* value(const  ::myrabot_arm_base::WriteServos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::myrabot_arm_base::WriteServos_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::myrabot_arm_base::WriteServos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.posicion);
    stream.next(m.velocidad);
    stream.next(m.par);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WriteServos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myrabot_arm_base::WriteServos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::myrabot_arm_base::WriteServos_<ContainerAllocator> & v) 
  {
    s << indent << "posicion: ";
s << std::endl;
    Printer< ::myrabot_arm_base::Servos_<ContainerAllocator> >::stream(s, indent + "  ", v.posicion);
    s << indent << "velocidad: ";
s << std::endl;
    Printer< ::myrabot_arm_base::Servos_<ContainerAllocator> >::stream(s, indent + "  ", v.velocidad);
    s << indent << "par: ";
s << std::endl;
    Printer< ::myrabot_arm_base::Servos_<ContainerAllocator> >::stream(s, indent + "  ", v.par);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MYRABOT_ARM_BASE_MESSAGE_WRITESERVOS_H

